In [501]:
import pandas as pd
import numpy as np

In [502]:
df=pd.read_csv("/content/indicators1(Data).csv")

In [503]:
df

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,4.4,9.3,14.1,19,23.8,28.7,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,85.3
1,Afghanistan,AFG,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,36.28907741,37.06956358,54.50542721,50.73187703
2,Afghanistan,AFG,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,..,-11.77453603,6.125522029,11.65523822,11.27143206,10.91277355,...,0.566944543,2.447563001,-2.197526467,2.403656188,2.071348578,6.521479848,6.962946255,2.838996251,9.406239339,2.923662131
3,Afghanistan,AFG,Natural gas rents (% of GDP),NY.GDP.NGAS.RT.ZS,..,..,0.231561307,0.0367297,0.028302171,0.023093937,...,0.00462182,0.002152592,0.002130179,0.001937332,0.001512027,0.001527189,0.001347551,0.001953539,..,..
4,Afghanistan,AFG,Trade (% of GDP),NE.TRD.GNFS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,46.70989455,51.41171637,72.88546961,67.58466515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5320,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5321,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5322,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5323,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5324,Last Updated: 10/07/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [504]:
df.shape

(5325, 28)

In [505]:
df.columns = df.columns.str.replace(r"\s+\[YR\d+\]", "", regex=True)

df = df.rename(columns={
    "Country Code": "ISO",
    "Country Name": "Country",
})

In [506]:
df.isnull().mean()*100

Country        0.056338
ISO            0.093897
Series Name    0.093897
Series Code    0.093897
2000           0.093897
2001           0.093897
2002           0.093897
2003           0.093897
2004           0.093897
2005           0.093897
2006           0.093897
2007           0.093897
2008           0.093897
2009           0.093897
2010           0.093897
2011           0.093897
2012           0.093897
2013           0.093897
2014           0.093897
2015           0.093897
2016           0.093897
2017           0.093897
2018           0.093897
2019           0.093897
2020           0.093897
2021           0.093897
2022           0.093897
2023           0.093897
dtype: float64

In [507]:
mis = df.isna().mean() * 100

print(mis)

Country        0.056338
ISO            0.093897
Series Name    0.093897
Series Code    0.093897
2000           0.093897
2001           0.093897
2002           0.093897
2003           0.093897
2004           0.093897
2005           0.093897
2006           0.093897
2007           0.093897
2008           0.093897
2009           0.093897
2010           0.093897
2011           0.093897
2012           0.093897
2013           0.093897
2014           0.093897
2015           0.093897
2016           0.093897
2017           0.093897
2018           0.093897
2019           0.093897
2020           0.093897
2021           0.093897
2022           0.093897
2023           0.093897
dtype: float64

In [508]:
bad_entries = [
    "Eastern Africa",
    "Western Africa",
    "Southern Africa",
    "World",
    "European Union",
    "South Asia",
    "East Asia & Pacific",
    "Arab World",
    "Central Europe and the Baltics",
    "Data from database: World Development Indicators",
    "Caribbean small states",
    "Northern Mariana Islands",
    "Central African Republic",
    "Channel Islands",
    "Early-demographic dividend",
    "East Asia & Pacific (excluding high income)",
    "East Asia & Pacific (IDA & IBRD countries)",
    "Europe & Central Asia",
    "Europe & Central Asia (excluding high income)",
    "Europe & Central Asia (IDA & IBRD countries)",
    "Faroe Islands",
    "Fragile and conflict affected situations",
    "Heavily indebted poor countries (HIPC)",
    "High income",
    "IBRD only",
    "IDA & IBRD total",
    "IDA blend",
    "IDA only",
    "IDA total",
    "Isle of Man",
    "Late-demographic dividend",
    "Latin America & Caribbean (excluding high income)",
    "Latin America & Caribbean",
    "Latin America & the Caribbean (IDA & IBRD countries)",
    "Least developed countries: UN classification",
    "Low income",
    "Low & middle income",
    "Lower middle income",
    "Marshall Islands",
    "Middle East, North Africa, Afghanistan & Pakistan",
    "Middle income",
    "Middle East, North Africa, Afghanistan & Pakistan (IDA & IBRD)",
    "Middle East, North Africa, Afghanistan & Pakistan (excluding high income)",
    "North America",
    "Northern Mariana Islands",
    "Not classified",
    "OECD members",
    "Other small states",
    "Pacific island small states",
    "Post-demographic dividend",
    "Sint Maarten (Dutch part)",
    "Small states",
    "Solomon Islands",
    "South Africa",
    "South Asia (IDA & IBRD)",
    "St. Martin (French part)",
    "Sub-Saharan Africa",
    "Sub-Saharan Africa (excluding high income)",
    "Sub-Saharan Africa (IDA & IBRD countries)",
    "Turks and Caicos Islands",
    "United Arab Emirates",
    "United Kingdom",
    "Upper middle income",
    "Virgin Islands (U.S.)",
    "West Bank and Gaza"
]

df = df[~df["Country"].isin(bad_entries)].reset_index(drop=True)

In [509]:
df

,Country,ISO,Series Name,Series Code,2000,2001,2002,2003,2004,2005,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,4.4,9.3,14.1,19,23.8,28.7,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,85.3
1,Afghanistan,AFG,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,36.28907741,37.06956358,54.50542721,50.73187703
2,Afghanistan,AFG,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,..,-11.77453603,6.125522029,11.65523822,11.27143206,10.91277355,...,0.566944543,2.447563001,-2.197526467,2.403656188,2.071348578,6.521479848,6.962946255,2.838996251,9.406239339,2.923662131
3,Afghanistan,AFG,Natural gas rents (% of GDP),NY.GDP.NGAS.RT.ZS,..,..,0.231561307,0.0367297,0.028302171,0.023093937,...,0.00462182,0.002152592,0.002130179,0.001937332,0.001512027,0.001527189,0.001347551,0.001953539,..,..
4,Afghanistan,AFG,Trade (% of GDP),NE.TRD.GNFS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,46.70989455,51.41171637,72.88546961,67.58466515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4119,Zimbabwe,ZWE,Urban population,SP.URB.TOTL,4014520,4090799,4180515,4217583,4240760,4258099,...,4617960,4663120,4715311,4775100,4842447,4918908,5006179,5102973,5205571,5313545
4120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4123,Last Updated: 10/07/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [510]:
df.shape

(4124, 28)

In [511]:
df = df.drop_duplicates()

df = df.reset_index(drop=True)

In [512]:
df.shape

(4122, 28)

In [513]:
df = df.replace("..", np.nan)

In [514]:
df

,Country,ISO,Series Name,Series Code,2000,2001,2002,2003,2004,2005,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,4.4,9.3,14.1,19,23.8,28.7,...,89.5,71.5,97.7,97.7,93.4,97.7,97.7,97.7,85.3,85.3
1,Afghanistan,AFG,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,36.28907741,37.06956358,54.50542721,50.73187703
2,Afghanistan,AFG,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,NaN,-11.77453603,6.125522029,11.65523822,11.27143206,10.91277355,...,0.566944543,2.447563001,-2.197526467,2.403656188,2.071348578,6.521479848,6.962946255,2.838996251,9.406239339,2.923662131
3,Afghanistan,AFG,Natural gas rents (% of GDP),NY.GDP.NGAS.RT.ZS,NaN,NaN,0.231561307,0.0367297,0.028302171,0.023093937,...,0.00462182,0.002152592,0.002130179,0.001937332,0.001512027,0.001527189,0.001347551,0.001953539,NaN,NaN
4,Afghanistan,AFG,Trade (% of GDP),NE.TRD.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,46.70989455,51.41171637,72.88546961,67.58466515
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4117,Zimbabwe,ZWE,"Population, female",SP.POP.TOTL.FE.IN,6233089,6282984,6346623,6424049,6498530,6567254,...,7491842,7588874,7690502,7797375,7908981,8027926,8156300,8291728,8426339,8559888
4118,Zimbabwe,ZWE,"Population, male",SP.POP.TOTL.MA.IN,5658966,5688917,5741030,5808274,5867366,5916178,...,6715517,6810139,6909792,7015107,7125471,7243442,7370588,7505482,7642717,7780934
4119,Zimbabwe,ZWE,Urban population,SP.URB.TOTL,4014520,4090799,4180515,4217583,4240760,4258099,...,4617960,4663120,4715311,4775100,4842447,4918908,5006179,5102973,5205571,5313545
4120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4121,Last Updated: 10/07/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [515]:
missing_vals = ["..", "", "NA", "n/a", "N/A"]


df = df.replace(missing_vals, np.nan)


year_cols = [str(y) for y in range(2000, 2025)]
for col in year_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

In [516]:
missing_percentage = df.isna().mean() * 100

print(missing_percentage)

Country         0.024260
ISO             0.048520
Series Name     0.048520
Series Code     0.048520
2000           17.709850
2001           18.025230
2002           16.739447
2003           16.375546
2004           16.254246
2005           15.332363
2006           15.138282
2007           15.065502
2008           14.531781
2009           14.434740
2010           14.216400
2011           14.119360
2012           13.731198
2013           14.022319
2014           13.634158
2015           13.585638
2016           13.876759
2017           14.095099
2018           15.356623
2019           17.588549
2020           18.292091
2021           18.971373
2022           31.538088
2023           37.069384
dtype: float64

In [517]:
missing_vals = ["..", "", "NA", "N/A", "n/a"]


df = df.replace(missing_vals, np.nan)

In [518]:
df

,Country,ISO,Series Name,Series Code,2000,2001,2002,2003,2004,2005,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,4.4,9.300000e+00,1.410000e+01,1.900000e+01,2.380000e+01,2.870000e+01,...,8.950000e+01,7.150000e+01,9.770000e+01,9.770000e+01,9.340000e+01,9.770000e+01,9.770000e+01,9.770000e+01,8.530000e+01,8.530000e+01
1,Afghanistan,AFG,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.628908e+01,3.706956e+01,5.450543e+01,5.073188e+01
2,Afghanistan,AFG,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,NaN,-1.177454e+01,6.125522e+00,1.165524e+01,1.127143e+01,1.091277e+01,...,5.669445e-01,2.447563e+00,-2.197526e+00,2.403656e+00,2.071349e+00,6.521480e+00,6.962946e+00,2.838996e+00,9.406239e+00,2.923662e+00
3,Afghanistan,AFG,Natural gas rents (% of GDP),NY.GDP.NGAS.RT.ZS,NaN,NaN,2.315613e-01,3.672970e-02,2.830217e-02,2.309394e-02,...,4.621820e-03,2.152592e-03,2.130179e-03,1.937332e-03,1.512027e-03,1.527189e-03,1.347551e-03,1.953539e-03,NaN,NaN
4,Afghanistan,AFG,Trade (% of GDP),NE.TRD.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.670989e+01,5.141172e+01,7.288547e+01,6.758467e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4117,Zimbabwe,ZWE,"Population, female",SP.POP.TOTL.FE.IN,6233089.0,6.282984e+06,6.346623e+06,6.424049e+06,6.498530e+06,6.567254e+06,...,7.491842e+06,7.588874e+06,7.690502e+06,7.797375e+06,7.908981e+06,8.027926e+06,8.156300e+06,8.291728e+06,8.426339e+06,8.559888e+06
4118,Zimbabwe,ZWE,"Population, male",SP.POP.TOTL.MA.IN,5658966.0,5.688917e+06,5.741030e+06,5.808274e+06,5.867366e+06,5.916178e+06,...,6.715517e+06,6.810139e+06,6.909792e+06,7.015107e+06,7.125471e+06,7.243442e+06,7.370588e+06,7.505482e+06,7.642717e+06,7.780934e+06
4119,Zimbabwe,ZWE,Urban population,SP.URB.TOTL,4014520.0,4.090799e+06,4.180515e+06,4.217583e+06,4.240760e+06,4.258099e+06,...,4.617960e+06,4.663120e+06,4.715311e+06,4.775100e+06,4.842447e+06,4.918908e+06,5.006179e+06,5.102973e+06,5.205571e+06,5.313545e+06
4120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4121,Last Updated: 10/07/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [519]:
df

,Country,ISO,Series Name,Series Code,2000,2001,2002,2003,2004,2005,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Afghanistan,AFG,Access to electricity (% of population),EG.ELC.ACCS.ZS,4.4,9.300000e+00,1.410000e+01,1.900000e+01,2.380000e+01,2.870000e+01,...,8.950000e+01,7.150000e+01,9.770000e+01,9.770000e+01,9.340000e+01,9.770000e+01,9.770000e+01,9.770000e+01,8.530000e+01,8.530000e+01
1,Afghanistan,AFG,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.628908e+01,3.706956e+01,5.450543e+01,5.073188e+01
2,Afghanistan,AFG,"Inflation, GDP deflator (annual %)",NY.GDP.DEFL.KD.ZG,NaN,-1.177454e+01,6.125522e+00,1.165524e+01,1.127143e+01,1.091277e+01,...,5.669445e-01,2.447563e+00,-2.197526e+00,2.403656e+00,2.071349e+00,6.521480e+00,6.962946e+00,2.838996e+00,9.406239e+00,2.923662e+00
3,Afghanistan,AFG,Natural gas rents (% of GDP),NY.GDP.NGAS.RT.ZS,NaN,NaN,2.315613e-01,3.672970e-02,2.830217e-02,2.309394e-02,...,4.621820e-03,2.152592e-03,2.130179e-03,1.937332e-03,1.512027e-03,1.527189e-03,1.347551e-03,1.953539e-03,NaN,NaN
4,Afghanistan,AFG,Trade (% of GDP),NE.TRD.GNFS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.670989e+01,5.141172e+01,7.288547e+01,6.758467e+01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4117,Zimbabwe,ZWE,"Population, female",SP.POP.TOTL.FE.IN,6233089.0,6.282984e+06,6.346623e+06,6.424049e+06,6.498530e+06,6.567254e+06,...,7.491842e+06,7.588874e+06,7.690502e+06,7.797375e+06,7.908981e+06,8.027926e+06,8.156300e+06,8.291728e+06,8.426339e+06,8.559888e+06
4118,Zimbabwe,ZWE,"Population, male",SP.POP.TOTL.MA.IN,5658966.0,5.688917e+06,5.741030e+06,5.808274e+06,5.867366e+06,5.916178e+06,...,6.715517e+06,6.810139e+06,6.909792e+06,7.015107e+06,7.125471e+06,7.243442e+06,7.370588e+06,7.505482e+06,7.642717e+06,7.780934e+06
4119,Zimbabwe,ZWE,Urban population,SP.URB.TOTL,4014520.0,4.090799e+06,4.180515e+06,4.217583e+06,4.240760e+06,4.258099e+06,...,4.617960e+06,4.663120e+06,4.715311e+06,4.775100e+06,4.842447e+06,4.918908e+06,5.006179e+06,5.102973e+06,5.205571e+06,5.313545e+06
4120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4121,Last Updated: 10/07/2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [520]:
df.shape

(4122, 28)

In [521]:



non_numeric_cols = ["Country", "ISO", "Series Name", "Series Code"]
num_cols = [col for col in df.columns if col not in non_numeric_cols]


for col in num_cols:

    df[col] = (
        df[col]
        .astype(str)
        .str.replace(",", "", regex=False)
        .str.strip()
    )


    df[col] = pd.to_numeric(df[col], errors="coerce")



# impossible values
invalid_masks = {}

for col in num_cols:
    mask = (df[col] < 0) | (df[col] > 1e12)  # adjust threshold as needed
    if mask.sum() > 0:
        invalid_masks[col] = mask



for col, mask in invalid_masks.items():
    print(f"Column '{col}' has {mask.sum()} suspicious values:")
    print(df.loc[mask, [col]].head())


#  extreme values

for col, mask in invalid_masks.items():
    df.loc[mask, col] = np.nan

Column '2000' has 50 suspicious values:
          2000
153  -9.201606
202  -1.373676
213 -17.541569
293 -26.087086
333  -3.500303
Column '2001' has 52 suspicious values:
          2001
2   -11.774536
153 -25.990003
182  -1.095768
213 -10.929250
222  -2.835502
Column '2002' has 44 suspicious values:
          2002
213  -6.353616
293  -4.549573
333  -3.037741
602  -0.135384
673 -31.342859
Column '2003' has 44 suspicious values:
          2003
162  -0.479330
422  -4.107504
453  -0.504159
673 -45.265079
873  -1.788425
Column '2004' has 34 suspicious values:
          2004
102  -3.259075
333  -1.778660
673 -35.460818
682  -6.332547
913 -52.263298
Column '2005' has 29 suspicious values:
          2005
53   -7.469723
102  -1.365583
233 -10.927445
373  -1.907142
673 -22.092231
Column '2006' has 23 suspicious values:
          2006
53   -8.907729
642  -0.662827
673 -25.073330
893 -14.952896
913 -23.602039
Column '2007' has 27 suspicious values:
          2007
53   -8.363494
233  -6.019501
633  -4.718552
673 -35.963545
782  -1.756662
Column '2008' has 27 suspicious values:
          2008
33   -0.403265
153  -8.139656
673 -44.549290
733  -1.207070
893 -29.681907
Column '2009' has 74 suspicious values:
          2009
2    -2.163404
82   -7.373748
142 -16.762140
153  -0.941489
282 -18.899228
Column '2010' has 40 suspicious values:
          2010
102 -15.364890
222  -1.223407
233  -1.139594
302  -0.392566
673 -28.612203
Column '2011' has 43 suspicious values:
         2011
102 -0.523560
213 -1.315074
233 -8.977894
302 -0.858605
333 -5.632537
Column '2012' has 46 suspicious values:
          2012
362  -1.017542
373  -3.069252
573  -0.323742
673 -15.005483
733  -4.118263
Column '2013' has 52 suspicious values:
         2013
162 -2.287572
222 -1.995948
242 -0.163601
373 -0.946046
522 -0.224122
Column '2014' has 59 suspicious values:
         2014
102 -0.962160
122 -0.084019
282 -1.330204
322 -1.440437
373 -1.165849
Column '2015' has 69 suspicious values:
         2015
82  -4.986745
142 -3.518385
242 -0.623858
282 -8.809616
322 -8.756673
Column '2016' has 51 suspicious values:
         2016
2   -2.197526
62  -0.864265
162 -0.475118
222 -1.002800
242 -0.663158
Column '2017' has 37 suspicious values:
         2017
102 -1.940890
153 -3.190404
222 -3.178167
373 -2.496541
442 -0.367898
Column '2018' has 29 suspicious values:
          2018
153  -4.851983
573  -4.529078
662  -2.850859
673 -17.756003
893  -3.545924
Column '2019' has 45 suspicious values:
         2019
73  -1.355321
213 -3.265516
282 -0.221653
422 -0.117835
442 -0.397554
Column '2020' has 74 suspicious values:
         2020
73  -2.355145
82  -4.711384
222 -0.951474
233 -2.678666
282 -7.493633
Column '2021' has 32 suspicious values:
         2021
222 -4.912625
302 -1.220813
513 -1.609146
573 -0.081120
733 -0.244821
Column '2022' has 4 suspicious values:
           2022
1082  -0.147759
2022  -1.958672
2462  -0.612362
2702 -13.365341
Column '2023' has 26 suspicious values:
          2023
282  -9.322615
322  -4.284372
502  -0.505250
602 -12.847251
822  -0.505705

In [522]:
year_cols = [str(y) for y in range(2000, 2024)]
for col in year_cols:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')


df[year_cols] = df[year_cols].fillna(df[year_cols].median())

In [523]:
import pandas as pd
from google.colab import files


df.to_csv("cleaned_indicator1.csv", index=False)


files.download("cleaned_indicator1.csv")